### ISSUE TITLE
Getting "Failed to Initialize VapourSynth environment" and "pipe:: Invalid data found when processing output"

### ISSUE THREAD

**Issue by cutieion** [f0e/blur#1]
Whenever I drag a video clip in, I get these errors. I downloaded all the dependencies and files required for it to run normally and I got these errors.

**Comment by hhhhh114451** [comment]
same issue, find a solution yet?

**Comment by cutieion** [comment]
nope nothin

**Comment by f0e** [comment]
seems like this is an issue when python can't find vapoursynth.dll
when vapoursynth installs it should create 'vapoursynth.dll' in your python site-packages folder. for me, this file's stored in C:\Python39\Lib\site-packages.
you can run `python -c "import sys; print('\n'.join(sys.path))"` in command prompt to see all the directories which python uses, vapoursynth.dll should be in one of those.

if you can't find it then try finding out where it is.

only thing i can suggest other than that is just try reinstalling python and vapoursynth and installing both for all users, or you can just do it all through installer.bat and it should work properly
