### ISSUE TITLE
Add blur as a PATH environment variable.

### ISSUE THREAD

**Issue by Aetopia** [f0e/blur#11]
# **Add `blur` as a PATH environment variable.**

### How this will be useful?:

1. Adding `blur` as a PATH environment variable can make its CLI interface more convenient and easier to use.
2. This can make `blur` accessible in any directory and any terminal. (Powershell, CMD, Windows Terminal)
3. The user won't be forced to be access `C:\Program Files (x86)\blur` everytime if they want use `blur`'s CLI interface.

**Comment by f0e** [comment]
done, added it as an option in the latest installer
