### ISSUE TITLE
Wrong path error

### ISSUE THREAD

**Issue by ThomasLQV** [f0e/blur#12]
So I did all the requirements properly then I dropped a video to the window and it says the video couldn't be opened (wrong path?)
It looks like this:
![image](https://user-images.githubusercontent.com/94176230/141466166-501daed0-a785-42ec-8e15-300f798f4089.png)

Can someone tell me how to fix this?

Thank you.

**Comment by couleurm** [comment]
Hey, does the path of your video/it's name contain any non-alphanumeric character(s)? Is your video located on another drive?

**Comment by ThomasLQV** [comment]
No, it is located on the same drive, and its name/path has no special characters.

**Comment by couleurm** [comment]
Do you get the same error when using blur through the command line?

**Comment by ThomasLQV** [comment]
What command line?
(im new bruh)

**Comment by ThomasLQV** [comment]
> Do you get the same error when using blur through the command line?

Oh, thank you I did it through cmd and it worked, and again thank you!

**Comment by MagloYT** [comment]
> Do you get the same error when using blur through the command line?

hello? i have the same issue as well and i dont know how to open Blur through the cmd
