### ISSUE TITLE
Error when using Blur

### ISSUE THREAD

**Issue by Varlay** [f0e/blur#14]
Hey, I had this problem when I installed Blur for the first time (Nov. 28 2021).
When I dragged my video in with my config setting set, this message pops up.

-----------------------------------------------------------------------------------------------------------
Script evaluation failed:
Python exception: No attribute with the name fmtc exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2242, in vapoursynth.vpy_evaluateScript
  File "src\cython\vapoursynth.pyx", line 2243, in vapoursynth.vpy_evaluateScript
  File "E:\\\blur_temp\8y2GKr.vpy", line 8, in <module>
    video = core.fmtc.matrix(clip=video, mat="601", col_fam=vs.YUV, bits=16)
  File "src\cython\vapoursynth.pyx", line 1891, in vapoursynth._CoreProxy.__getattr__
  File "src\cython\vapoursynth.pyx", line 1754, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name fmtc exists. Did you mistype a plugin namespace?
-----------------------------------------------------------------------------------------------------------
My current settings are below.
[Current Settings.txt](https://github.com/f0e/blur/files/7613123/Current.Settings.txt)

Thanks.

**Comment by Varlay** [comment]
Addition: On the line "#######PUTYOURGPUHERE###########" it's supposed to be "nvidia". Sorry if this mixs up something.

**Comment by applesfruit** [comment]
In this case, you would want to use CPU rendering, as you put CPU ffmpeg filters. So your config would look something like
[Current.Settings.txt](https://github.com/f0e/blur/files/7781387/Current.Settings.txt)
:

**Comment by applesfruit** [comment]
It may not work, just try it. If it doesn't work then reply to this issue.

**Comment by f0e** [comment]
closed due to inactivity and possible duplicate of #21, #23
