### ISSUE TITLE
Multiqueue Support

### ISSUE THREAD

**Issue by Aetopia** [f0e/blur#17]
As the title suggests, allow the user to queue multiple video files natively.

```py
import sys
import subprocess
Videos=sys.argv[1:len(sys.argv)]
for Index in range(len(Videos)):
    print("Video:",Videos[Index])
    subprocess.run(["C:/Program Files (x86)/blur/blur.exe","--noui","--nopreview","--input", Videos[Index]])
    print("")
````
Here is a basic Python Script which emulates this behavior.

**Comment by couleurm** [comment]
iirc you can just do `-i video_1.mp4 -i video_2.mp4 -i video_3.mp4` and so on

**Comment by Aetopia** [comment]
So you can't use a single `-i` for multi queue?

**Comment by applesfruit** [comment]
Try it, I doubt f0e will respond, he's been inactive lately.

**Comment by f0e** [comment]
> iirc you can just do `-i video_1.mp4 -i video_2.mp4 -i video_3.mp4` and so on

yep
