### ISSUE TITLE
¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by movemente** [f0e/blur#2]
![image](https://user-images.githubusercontent.com/87902551/126869464-277e614a-81f2-430f-ae75-84dfbfb0bfcb.png)

**Comment by DOG248** [comment]
You don't have the [requirements](https://github.com/f0e/blur#requirements)

**Comment by movemente** [comment]
I do, I used the installer, but it can't open .py files prob

**Comment by DOG248** [comment]
> I do, I used the installer, but it can't open .py files prob

Reinstall Python and vapoursynth 64. Remember, the python NEEDS to be the 3.9.
