### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by DannyGrey7** [f0e/blur#20]
I've been encountering this error a lot that stops it from rendering an entire video. It often happens on longer videos, anything less than a minute would mostly finish fine.
![blur_ihpYL8SytF](https://user-images.githubusercontent.com/31848459/159094902-c582b45e-90a4-4779-bc66-1f0b200312b3.png)

Any solutions for this?

**Comment by couleurm** [comment]
Preview is broken, turn it off and it won't happen
