### ISSUE TITLE
VIDEO COULDN'T BE OPENED WRONG PATH

### ISSUE THREAD

**Issue by EzyXD** [f0e/blur#24]
when i drag my video in blur do this error (the video path is mp4
![Screenshot_2](https://user-images.githubusercontent.com/82627156/167281773-47da50a9-9379-4ff4-a221-4311cf3d6ea5.png)
)

**Comment by Neruxov** [comment]
Make sure the video is on the same disk as the program itself, also make sure it doesn't include any non-alphanumeric symbols in its file name.

**Comment by Jayy182** [comment]
![z5237966161020_f725bbdc6958049f388cab12e7c97035](https://github.com/f0e/blur/assets/162954489/3394f5fa-480a-4008-9657-9d81875baa7b)

how to fix error ?
