### ISSUE TITLE
idk how to download

### ISSUE THREAD

**Issue by Ptridman** [f0e/blur#3]
How do i download 
Automatic:

Download the latest release or build the project.
Download and run installer.bat to automatically install all of the requirements.

because when i click on  "installer.bat" it open me a page but dont download

**Comment by DOG248** [comment]
Can you send the url?

**Comment by DOG248** [comment]
You need to Press the hotkey **CONTROL S** to download it.

**Comment by couleurm** [comment]
and don't forget to remove the '.txt' it may add

**Comment by Ptridman** [comment]
THANK YOU SO MUCH
