### ISSUE TITLE
Manual install SVPflow

### ISSUE THREAD

**Issue by enoaa86** [f0e/blur#31]
_Couldn't find VapourSynth plugins folder, try manually installing SVPflow._
VapourSynth is not found in the folders, therefore "person" is incapable of installing
SVPflow manually as they would not know what the compatible version would be.

f0e / blur v1.8

-

![image1](https://user-images.githubusercontent.com/97244352/203102020-3af3113e-b214-43e5-9b4c-91bf08619811.PNG)
![image2](https://user-images.githubusercontent.com/97244352/203102039-964b98a4-0e9b-4579-98fa-caffb871d3c2.PNG)
![image3](https://user-images.githubusercontent.com/97244352/203102056-9d22ce1c-9238-4fff-8837-1b5e042570a4.PNG)
![image4](https://user-images.githubusercontent.com/97244352/203102064-ea133927-e44e-4f3c-859b-17dbe459f2f5.PNG)
![image5](https://user-images.githubusercontent.com/97244352/203102067-7a4ee502-598e-4bf1-8151-852dc47e97c5.jpg)

**Comment by couleurm** [comment]
Use [blur-installer.exe](https://github.com/f0e/blur/releases/download/v1.8/blur-installer.exe) from releases to install blur

**Comment by enoaa86** [comment]
> Use [blur-installer.exe](https://github.com/f0e/blur/releases/download/v1.8/blur-installer.exe) from releases to install blur

Thank you for the answer!
