### ISSUE TITLE
Can you make one for mac?

### ISSUE THREAD

**Issue by Avyukt-Ballari** [f0e/blur#35]
plz

**Comment by floricraft** [comment]
why do u even use mac in the first place?

**Comment by couleurm** [comment]
I don't know any Mac users who use blur, let alone those who have the knowledge to port it to MacOS, install VapourSynth and compile it. Good luck

Blur acts as a wrapper for VapourSynth so you could drop blur and run vpy scripts yourself

**Comment by f0e** [comment]
making a mac/linux version is not planned at the moment, https://github.com/couleur-tweak-tips/smoothie might be what you're looking for

**Comment by couleurm** [comment]
for the other people looking around:

you might have more luck using the mac os package manager brew.sh
<https://formulae.brew.sh/formula/vapoursynth#default>

**Comment by Avyukt-Ballari** [comment]
@f0e its for linux, should i try for mac?
