### ISSUE TITLE
Add support for image sequences

### ISSUE THREAD

**Issue by mikota** [f0e/blur#54]
Please add support for tga/png image sequences as input.

This is important because many game clients support image sequence export for high-framerate recordings, and those are preferred because of quality (lossless) and speed of recording (usually it's much faster to use an in-game imgseq export to get 3600fps footage rather than to record in 60fps obs with `0.01666` timescale).

Thank you for this amazing program.

**Comment by couleurm** [comment]
I don't know any VapourSynth source plugins that support this, though you could probably package these frames into a lossless video [with FFmpeg](https://video.stackexchange.com/questions/7903/how-to-losslessly-encode-a-jpg-image-sequence-to-a-video-in-ffmpeg)

also I'd be curious to know what games you play that support exporting high fps replays 👁

**Comment by Z1xus** [comment]
must be some source based game

**Comment by mikota** [comment]
> I don't know any VapourSynth source plugins that support this, though you could probably package these frames into a lossless video [with FFmpeg](https://video.stackexchange.com/questions/7903/how-to-losslessly-encode-a-jpg-image-sequence-to-a-video-in-ffmpeg)
> 
> also I'd be curious to know what games you play that support exporting high fps replays 👁

I understand, thank you.

 To answer your question, most Quake-engine and derived engines/source-ports support this. Some of them also support a specific video format with some customization options, and some have full ffmpeg support for such stuff. I found that image sequence export is by far the most common denominator though, and is usually the simplest to setup, therefore the question.
