### ISSUE TITLE
weighting.py link dead

### ISSUE THREAD

**Issue by lapentad** [f0e/blur#6]
weighting.py link in the installer is dead.

I replaced it with 
`powershell Invoke-WebRequest "https://raw.githubusercontent.com/f0e/blur/v1.5/weighting.py" -OutFile "%temp%\weighting.py"`

**Comment by couleurm** [comment]
Hey, weighting.py was moved in a new folder called plugins, here's the link to it.
https://github.com/f0e/blur/blob/master/plugins/weighting.py
