### ISSUE TITLE
Invalid data found when processing input-

### ISSUE THREAD

**Issue by MaybeKashu** [f0e/blur#68]
![Screenshot 2023-10-11 221755](https://github.com/f0e/blur/assets/147647017/8171da37-c041-45dc-8305-b64e3769ffa0)
okay so ive been facing this problem for a while now
ive tried : - restarting my laptop
                   -reinstalling blur
                  - reinstalling the config thing              
                                                                                 Someone please help.

**Comment by couleurm** [comment]
try reinstalling blur, vapoursynth fails to initialize and ffmpeg reads nothing from it

**Comment by MaybeKashu** [comment]
> try reinstalling blur, vapoursynth fails to initialize and ffmpeg reads nothing from it

tysm <3

**Comment by MaybeKashu** [comment]
> try reinstalling blur, vapoursynth fails to initialize and ffmpeg reads nothing from it

tysm<3
