### ISSUE TITLE
Attribute error? vapoursynth ?

### ISSUE THREAD

**Issue by vecnhan** [f0e/blur#69]
I was using blur without frame interpolation because CUDA wasn't working I think that because I didn't download the rilfe when I installing blur using the blur installation and switched back to the default setting and it still did not work lol. help T.T
thanks
![image](https://github.com/f0e/blur/assets/50039764/d19c8baf-4759-4334-ae6a-6076eea31696)
![image](https://github.com/f0e/blur/assets/50039764/aff04639-b935-401c-a4f8-cbc1e5eff3b3)

**Comment by vecnhan** [comment]
![image](https://github.com/f0e/blur/assets/50039764/6fe91cdd-d000-49e1-8f3e-906d7af83893)

**Comment by vecnhan** [comment]
Just reinstall blur but it still happens only if I disable interpolation it works fine

**Comment by f0e** [comment]
closing since it looks like everything's working now
