### ISSUE TITLE
Script exceeded memory limit. consider raising cache size 

### ISSUE THREAD

**Issue by dodobestfriend** [f0e/blur#77]
It worked completely fine when i applied motion blur to my 1080p videos but now i keep getting this error message when applying it to my 4k ones

**Comment by couleurm** [comment]
Is this a critical error that crashes blur or is it a warning? I've experienced the latter

**Comment by dodobestfriend** [comment]
it doesn't really crash blur but it does make it not work as it's supposed to (as in the video isn't as smooth as it should've been)

**Comment by couleurm** [comment]
what point of reference are you taking when mentionning "it should have been"?
