### ISSUE TITLE
PLEASE ADD LINUX VERSION

### ISSUE THREAD

**Issue by boibest** [f0e/blur#92]
I ran it with wine and I cant drag in any files. And you could at least let us chose a custom directory to install blur.exe.

**Comment by boibest** [comment]
PLEASE ADD

**Comment by githubpub900** [comment]
use smoothie

**Comment by boibest** [comment]
yeah i couldn't get that to work either

**Comment by boibest** [comment]
githubpub900 i couldn't get that to work either so i guess i will never have good looking videos ... i wish foe read the issues

**Comment by f0e** [comment]
https://github.com/f0e/blur/issues/13
