### ISSUE TITLE
virus???

### ISSUE THREAD

**Issue by githubpub900** [f0e/blur#94]
idk, but triage says its a 7/10, on virustotal there is one detection, and microsoft defender says its safe,  what do i trust?

**Comment by githubpub900** [comment]
ok, it is a virus. personally this isn't the fault of f0e, its the installer wizard. adds a file called synaptics.exe. describes itself as a laptop touchpad driver and it does bad stuff, it has 53 DETECTIONS on virus total. It is located in  C:\ProgramData\Synaptics\

use the other method of installing blur, stay safe yall.

**Comment by githubpub900** [comment]
?

**Comment by f0e** [comment]
installer source is in the repo for anyone to look at. i can say it's safe but you shouldn't just take my word for it, this does just seem like a false positive though. inno setup (which is what i'm using to build the installer) is extremely widely used and known to be safe. closing
